services:

  wallet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      "SPRING_R2DBC_URL": "r2dbc:postgresql://postgresql:5432/demo?schema=wallet"
      "SPRING_FLYWAY_URL": "jdbc:postgresql://postgresql:5432/demo?schema=wallet"
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql: