# Spring Configuration
spring:
  application:
    name: "wallet-server"
  main:
    web-application-type: reactive
  cloud:
    vault:
      host: localhost
      port: 8201
      authentication: token
      token: hvs.V2MAmEtjgbOYfpbIYLA5QXCf
      scheme: http
      kv:
        enabled: true
    azure:
      keyvault:
        secret:
          endpoint: https://example

# Spring Logging Configuration
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    es.in2.wallet: INFO

# Spring Management Configuration - Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics, prometheus
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
        prometheus: prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    loggers:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true

# SpringDoc Configuration - OpenAPI 3.0 Documentation & Swagger UI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

# Server Configuration
server:
  port: 8080

# Context Broker Configuration
broker:
  provider: "scorpio"
  externalDomain: "http://localhost:9090"
  internalDomain: "http://localhost:9090"
  paths:
    entities: "/ngsi-ld/v1/entities"

vault:
  provider:
    name: hashicorp #hashicorp #azure

auth-server:
  domain: https://issuerkeycloak.demo.in2.es/realms/EAAProvider
  token-endpoint: https://issuerkeycloak.demo.in2.es/realms/EAAProvider/verifiable-credential/did:key:z6MkqmaCT2JqdUtLeKah7tEVfNXtDXtQyj4yxEgV11Y5CqUa/token
