spring:
  application:
    name: "wallet-server"
  main:
    web-application-type: reactive

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    es.in2.wallet: DEBUG

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics, prometheus
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
        prometheus: prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
      vault:
        enabled: false
    loggers:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    tracing:
      enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

server:
  port: 8081

broker:
  provider: scorpio
  external-url:
    scheme: http
    domain: localhost
    port: 9090
  internal-url:
    scheme: http
    domain: localhost
    port: 9090
  paths:
    entities: "/ngsi-ld/v1/entities"

app:
  config-source:
    name: yaml

vault:
  provider:
    name: hashicorp

hashicorp:
  vault:
    path: /kv
    host: localhost
    port: 8200
    scheme: http
    token: "hvs.48sBkFvHj3xK9c9s8xRdZws9"

auth-server:
  external-url:
    scheme: "http"
    domain: "localhost"
    port: "8080"
    path: "/cross-keycloak/realms/EAAProvider"
  internal-url:
    scheme: "http"
    domain: "localhost"
    port: "8080"
    path: "/realms/EAAProvider"
  token-url:
    scheme: "http"
    domain: "localhost"
    port: "8080"
    path: "/realms/EAAProvider/verifiable-credential/did:key:z6MkqmaCT2JqdUtLeKah7tEVfNXtDXtQyj4yxEgV11Y5CqUa/token"

ebsi:
  test:
    url: http://localhost:8080/realms/wallet/protocol/openid-connect/token
    client-secret: "fV51P8jFBo8VnFKMMuP3imw3H3i5mNck"
    client-id: user-registry-client
    username: adminWallet
    password: adminPass

wallet-wda:
  urls:
    - scheme: http
      domain: localhost
      port: 4200
