spring:
  application:
    # Defines the name of the application
    name: "wallet-server"
  main:
    # Specifies that this is a reactive application (Spring WebFlux)
    web-application-type: reactive
  r2dbc:
    # The database connection URL for R2DBC (REQUIRED)
    url: "r2dbc:postgresql://localhost:5434/wallet?schema=wallet"
    # The database username for R2DBC connections (REQUIRED)
    username: "postgres"
    # The database password for R2DBC connections (REQUIRED)
    password: "postgres"
  flyway:
    # The JDBC URL used by Flyway for database schema migrations (REQUIRED)
    url: "jdbc:postgresql://localhost:5434/wallet?schema=wallet"
    # Defines the path where Flyway should look for SQL migration scripts (Not in Helm)
    locations: classpath:db/migration
    # The database username used by Flyway to execute migrations (REQUIRED)
    user: "postgres"
    # The database password used by Flyway to execute migrations (REQUIRED)
    password: "postgres"
    # Specifies the default schema in which Flyway should apply migrations (Not in Helm)
    default-schema: wallet


logging:
  pattern:
    # (Not in Helm)
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    # Sets logging level for the custom package "es.in2.wallet" (OPTIONAL)
    es.in2.wallet: DEBUG

# (Not in Helm)
management:
  endpoints:
    # Disables all management endpoints by default
    enabled-by-default: false
    web:
      exposure:
        # Specifies the enabled management endpoints
        include: health, prometheus
      # Sets the base path for management endpoints
      base-path: /
      path-mapping:
        # Maps the health endpoint to /health
        health: health
        # Maps the Prometheus metrics endpoint to /prometheus
        prometheus: prometheus
  endpoint:
    health:
      # Enables the health endpoint
      enabled: true
      # Always show detailed health information
      show-details: always
      vault:
        enabled: false
    prometheus:
      enabled: true

# Not in Helm
springdoc:
  api-docs:
    # Configures the endpoint where the OpenAPI JSON documentation is available
    path: /api-docs
  swagger-ui:
    # Configures the path to access the Swagger UI web interface
    path: /swagger-ui.html
    # Specifies how tags are sorted in the UI
    tags-sorter: alpha
    # Specifies how operations are sorted within each tag in the UI
    operations-sorter: method

server:
  # Defines the port on which the application will run
  port: 8080

app:
  config-source:
    #currently can be yaml or azure (Not in Helm)
    name: yaml

# Not in Helm
azure:
  app:
    endpoint: ${APP_CONFIG_ENDPOINT}
    label:
      global: service-discovery

security:
  auth-server:
    # (REQUIRED) External URL of the authentication server, accessible by clients (e.g. frontend apps, browser).
    external-url:
    # (REQUIRED) Internal URL of the authentication server, used by services within the cluster or private network.
    internal-url:
  cors:
    # Defines (OPTIONAL) a list of allowed origins for Cross-Origin Resource Sharing (CORS) requests.
    # Useful to restrict access to specific frontend domains.
    allowedOrigins:
  # Configures vault providers to store user secret keys
  vault:
    provider:
      # Name of the vault provider to use (e.g. 'hashicorp' or 'azure').
      name: hashicorp
    hashicorp:
      # (REQUIRED) URL of the HashiCorp Vault server (e.g. http://vault:8200).
      url:
      # (REQUIRED) Token used to authenticate with HashiCorp Vault.
      token:
    azure:
      # (Not in Helm) Endpoint of the Azure Key Vault to store secrets.
      endpoint: "your-endpoint"


# These properties are used to pass the EBSI Holder Wallet Test
ebsi:
  test:
    # (REQUIRED)
    url: "https://keycloak-dev.ssihub.org/realms/in2-wallet/protocol/openid-connect/token"
    # (REQUIRED)
    client-secret:
    # (not in Helm)
    client-id: "user-registry-client"
    # (not in Helm)
    username: "defaultuser"
    # (REQUIRED)
    password: "defaultpassword"

